### PR TITLE
FBX SDK 2015.1

### PR DESCRIPTION
**Pull request by andreasmuller**
Hi, I've updated ofxFBX to use the 2015.1 SDK, I've been running it on Windows and OSX, seems to work fine.

The only thing is, what to do about the libraries. The debug one for VS2012-x86 is over 100MB, so it won't push to Github and with 64 bit coming around the corner it'll easily be a few hundred MB of library files for various architectures.

It's a shame you can't upload support files to somewhere on Github. Hosting them separately somewhere seems like the way to go, in a .zip the expands to the right folder structure, just wanted to get your take on it. 

/A

### CODE REVIEW

**Comment by micuat** [comment]
I tested it on Windows 8 + OF0.8.4 + VS2012 and it works. Original library's download link is
http://usa.autodesk.com/adsk/servlet/pc/item?siteID=123112&id=10775847
They don't have VS2015 binary so I haven't tested with OF0.9.0.

**Comment by NickHardeman** [comment]
Does this change anything to the osx libs? I haven't been able to find any change logs for the sdk versions.
I have been actively developing in the 'develop' branch. The added Windows support would be awesome and would be great to merge in.
Thank you @andreasmuller! Sorry for the delayed response. Thanks for the bump @micuat.

**Comment by andreasmuller** [comment]
Hi!

No worries at all.

It's a bit tricky at the moment, there's OSX libs compiled with libstdc++ or libc++ (right?), then on the Windows side OF is transitioning to VS 2015, which there aren't libs for as far as I can tell, they only go to VS 2013. That one is going to be painful for a while as all the addons transition.

**Comment by NickHardeman** [comment]
I have tested on 009 and the 2013 libs work on OSX. So I don't think I need to recompile with libstdc++ for 009 compatability?  
Looks like the new 2016 fbx sdk supports VS 2015. http://usa.autodesk.com/adsk/servlet/pc/item?id=24735038&siteID=123112

I think it would be useful to package everything as it is now and then work on getting the addon ready for 009. But I don't have much windows knowledge...

**Pull request merged**
